// This file was auto-generated by ML.NET Model Builder. 

using System;
using MLNetConsoleML.Model;

namespace MLNetConsoleML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Month = @"1-Jan",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual ProductSales with predicted ProductSales from sample data...\n\n");
            Console.WriteLine($"Month: {sampleData.Month}");
            Console.WriteLine($"\n\nPredicted ProductSales: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
